name: End-to-end tests
# This specifies the event that will trigger the workflow. In this case, the workflow will run on every push event to the repository.
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # can specify the browser type and headless mode
        with: 
          # browser: chrome
          # headless: true
          # spec: cypress/e2e/15-pageObject.cy.js
          command: npm run test:chrome

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/html/index.html
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES }}
          publish_dir: cypress/reports/html/ # Updated with your report directory