name: End-to-end tests
# This specifies the event that will trigger the workflow. In this case, the workflow will run on every push event to the repository.
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # can specify the browser type and headless mode
        with: 
          # browser: chrome
          # headless: true
          spec: cypress/e2e/15-pageObject.cy.js

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/html/index.html
        
      - name: Deploy Mochawesome Report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: cypress/reports/html